version: "3"

services:
  docusaurus:
    build: .
    ports:
      - 3001:3001
      - 35729:35729
    volumes:
      - ./src:/usr/src/app/src
      - ./static:/usr/src/app/static
      - ./docs:/usr/src/app/docs
      - ./blog:/usr/src/app/blog
      - ./sidebars.js:/usr/src/app/sidebars.js
